# -*- coding: utf-8 -*-
"""star

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q-qhzsd1cqYW27CEx3T3Y-u5x0uMDYSL
"""

#star pyramid
n = int(input("Enter the number of rows "))
m = (2*n)-2

for i in range(0,n):
    for j in range(0,m):
        print(end = " ")
    m = m - 1*1
    for j in range(0,i+1):
        print("* ", end ='')
    print(" ")

#star left site pyramid
n = int(input("Enter the number of rows "))
m = (2*n)-2

for i in range(0,n):
    for j in range(0,m):
        print(end = " ")
    m = m - 1+1
    for j in range(0,i+1):
        print("* ", end ='')
    print(" ")

#star right site pyramid
n = int(input("Enter the number of rows "))
m = (2*n)-2

for i in range(0,n):
    for j in range(0,m):
        print(end = " ")
    m = m - 1-1
    for j in range(0,i+1):
        print("* ", end ='')
    print(" ")

#stiar
n = int(input("Enter the number of rows "))
m = (2*n)-2

for i in range(0,n):
    for j in range(0,m):
        print(end = " ")
    m = m + 1
    for j in range(0,i+1):
        print("* ", end ='')
    print(" ")